apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-internal-search-api
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9027
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /prometheus
  liveness:
    initialDelay: 5
    path: /isAlive
  readiness:
    initialDelay: 5
    path: /isReady
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi
  webproxy: false
  vault:
    enabled: false
  ingresses:
    - https://pam-internal-search-api.nais.oera.no
  env:
    - name: ELASTIC_URL
      value: http://tpa-stilling-opendistro-elasticsearch.tpa:9200
