server:
  port: 9030
pam:
  elasticsearch:
    url: ${STILLINGESBACKEND_URL:http://localhost:9200}
spring:
  profiles:
    active: prod
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    mappings:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["prometheus", "metrics", "mappings"]
