micronaut:
  application:
    name: internalad-search-api
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
  server:
    cors:
      enabled: true
      configurations:
        web:
          maxAge: 4000
    port: 9027
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
elasticsearch:
  url: ${OPEN_SEARCH_URI:http://localhost:9200}
  user: ${OPEN_SEARCH_USERNAME:foo}
  password: ${OPEN_SEARCH_PASSWORD:bar}